language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: lis2WSCtavCg7XTy9Ka/TpEKd+1MIEOdKqkVn91SCv2fFfd2qkri0m6bj0Kdu05Ddv5XmEMuC41VOHzSByR30CBi9upsPgGLDvldnVmE6bqaqrCgD5lcc9e4OdDwlMak41gfc05mamr8pzeX9cNnYOatLRRyft9WIiMo9PWMXs1UjiS/gB6HLg6e7+doVf6Yf2DYp1xDRV8XK+CUnFdgUp1CJxDnRrHRFcd0Xm06HVoTZKiVDZUtunoGH/6BubVmiK29LmIi1Iyvubozc6qKLnKX7igjZipyx59X98NH2ds4XH+lOQ+tCzhtJ67hxKyo0VYIFNXLYlSOBr8vTuWkGgb/093jlt3/NzhlNS7LbK2ov8mSKUiEA0n6l1ywLn/A5M1XUZ0o8xAszGtb85dhzVM722Hga+bob0HAJmNpt6mC0YBq/wSI4RqUOW6O+f0yI/DezEJlRecL+BIZgZJKfLGsjWnA+q8PfJeZZ0bIaMwIY/iP7i8s6mZsgNu2mCYxThYMYq4SDqhmjOIwLpGxpUrcxroSB3CVFv96TbkclPUAbkq5DcCt81xyxMtqDNE3d/lfHsxNM/dw8bKSlgM+/Hfj0cIBe1741InJz488zIc6iMFFtzIfda67Hj0qBp69zZSnBhj6Yp8eCNcXRLVF0LNvrSHzwZHLCtXvfuqMWOs=
